//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLithio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public Articulos()
        {
            this.Costo_Concepto = new HashSet<Costo_Concepto>();
        }
    
        public int Id_Articulo { get; set; }
        public string Codigo_Articulo { get; set; }
        public string Nombre_Articulo { get; set; }
        public string Descripcion_Articulo { get; set; }
        public int Cantidad_Articulo { get; set; }
        public double Costo_Articulo { get; set; }
        public double Costo_Anterior_Articulo { get; set; }
        public int Id_Proveedor { get; set; }
        public int Id_Presentacion { get; set; }
    
        public virtual Presentaciones Presentaciones { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual ICollection<Costo_Concepto> Costo_Concepto { get; set; }
    }
}
