//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLithio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costos
    {
        public int Id_Costo { get; set; }
        public string DUA { get; set; }
        public int Numero_Costos { get; set; }
        public int Id_Articulo { get; set; }
        public string Codigo_Articulo { get; set; }
        public string Nombre_Articulo { get; set; }
        public int Id_Presentacion { get; set; }
        public int Unidades_Articulos { get; set; }
        public double Tipo_De_Cambio { get; set; }
        public double Costo_Por_Unidad_Dolares { get; set; }
        public double Subtotal_Costo_Dolares { get; set; }
        public double Porcentaje_Costo { get; set; }
        public double Total_Costo_Dolares { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Presentaciones Presentaciones { get; set; }
    }
}
