//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLithio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LithioBDEntities : DbContext
    {
        public LithioBDEntities()
            : base("name=LithioBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Articulos> Articulos { get; set; }
        public DbSet<Costo_Concepto> Costo_Concepto { get; set; }
        public DbSet<Costos> Costos { get; set; }
        public DbSet<Estado_Usuario> Estado_Usuario { get; set; }
        public DbSet<Paises> Paises { get; set; }
        public DbSet<Presentaciones> Presentaciones { get; set; }
        public DbSet<Proveedores> Proveedores { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int pa_ActualizarTokenRecuperacionPass(string correo_Electronico, string token)
        {
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_ActualizarTokenRecuperacionPass", correo_ElectronicoParameter, tokenParameter);
        }
    
        public virtual ObjectResult<pa_Articulos_ExisteArticulosCodigo_Result> pa_Articulos_ExisteArticulosCodigo(string codigo_Articulo)
        {
            var codigo_ArticuloParameter = codigo_Articulo != null ?
                new ObjectParameter("Codigo_Articulo", codigo_Articulo) :
                new ObjectParameter("Codigo_Articulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Articulos_ExisteArticulosCodigo_Result>("pa_Articulos_ExisteArticulosCodigo", codigo_ArticuloParameter);
        }
    
        public virtual ObjectResult<pa_Articulos_ExisteArticulosNombre_Result> pa_Articulos_ExisteArticulosNombre(string nombre_Articulo)
        {
            var nombre_ArticuloParameter = nombre_Articulo != null ?
                new ObjectParameter("Nombre_Articulo", nombre_Articulo) :
                new ObjectParameter("Nombre_Articulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Articulos_ExisteArticulosNombre_Result>("pa_Articulos_ExisteArticulosNombre", nombre_ArticuloParameter);
        }
    
        public virtual int pa_Articulos_Insert(string codigo_Articulo, string nombre_Articulo, string descripcion_Articulo, Nullable<int> cantidad_Articulo, Nullable<double> costo_Articulo, Nullable<double> costo_Anterior_Articulo, Nullable<int> id_Proveedor, Nullable<int> id_Presentacion)
        {
            var codigo_ArticuloParameter = codigo_Articulo != null ?
                new ObjectParameter("Codigo_Articulo", codigo_Articulo) :
                new ObjectParameter("Codigo_Articulo", typeof(string));
    
            var nombre_ArticuloParameter = nombre_Articulo != null ?
                new ObjectParameter("Nombre_Articulo", nombre_Articulo) :
                new ObjectParameter("Nombre_Articulo", typeof(string));
    
            var descripcion_ArticuloParameter = descripcion_Articulo != null ?
                new ObjectParameter("Descripcion_Articulo", descripcion_Articulo) :
                new ObjectParameter("Descripcion_Articulo", typeof(string));
    
            var cantidad_ArticuloParameter = cantidad_Articulo.HasValue ?
                new ObjectParameter("Cantidad_Articulo", cantidad_Articulo) :
                new ObjectParameter("Cantidad_Articulo", typeof(int));
    
            var costo_ArticuloParameter = costo_Articulo.HasValue ?
                new ObjectParameter("Costo_Articulo", costo_Articulo) :
                new ObjectParameter("Costo_Articulo", typeof(double));
    
            var costo_Anterior_ArticuloParameter = costo_Anterior_Articulo.HasValue ?
                new ObjectParameter("Costo_Anterior_Articulo", costo_Anterior_Articulo) :
                new ObjectParameter("Costo_Anterior_Articulo", typeof(double));
    
            var id_ProveedorParameter = id_Proveedor.HasValue ?
                new ObjectParameter("Id_Proveedor", id_Proveedor) :
                new ObjectParameter("Id_Proveedor", typeof(int));
    
            var id_PresentacionParameter = id_Presentacion.HasValue ?
                new ObjectParameter("Id_Presentacion", id_Presentacion) :
                new ObjectParameter("Id_Presentacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Articulos_Insert", codigo_ArticuloParameter, nombre_ArticuloParameter, descripcion_ArticuloParameter, cantidad_ArticuloParameter, costo_ArticuloParameter, costo_Anterior_ArticuloParameter, id_ProveedorParameter, id_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_Articulos_Select_Result> pa_Articulos_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Articulos_Select_Result>("pa_Articulos_Select");
        }
    
        public virtual int pa_Articulos_Update(Nullable<int> id_Articulo, string codigo_Articulo, string nombre_Articulo, string descripcion_Articulo, Nullable<int> cantidad_Articulo, Nullable<double> costo_Articulo, Nullable<double> costo_Anterior_Articulo, Nullable<int> id_Proveedor, Nullable<int> id_Presentacion)
        {
            var id_ArticuloParameter = id_Articulo.HasValue ?
                new ObjectParameter("Id_Articulo", id_Articulo) :
                new ObjectParameter("Id_Articulo", typeof(int));
    
            var codigo_ArticuloParameter = codigo_Articulo != null ?
                new ObjectParameter("Codigo_Articulo", codigo_Articulo) :
                new ObjectParameter("Codigo_Articulo", typeof(string));
    
            var nombre_ArticuloParameter = nombre_Articulo != null ?
                new ObjectParameter("Nombre_Articulo", nombre_Articulo) :
                new ObjectParameter("Nombre_Articulo", typeof(string));
    
            var descripcion_ArticuloParameter = descripcion_Articulo != null ?
                new ObjectParameter("Descripcion_Articulo", descripcion_Articulo) :
                new ObjectParameter("Descripcion_Articulo", typeof(string));
    
            var cantidad_ArticuloParameter = cantidad_Articulo.HasValue ?
                new ObjectParameter("Cantidad_Articulo", cantidad_Articulo) :
                new ObjectParameter("Cantidad_Articulo", typeof(int));
    
            var costo_ArticuloParameter = costo_Articulo.HasValue ?
                new ObjectParameter("Costo_Articulo", costo_Articulo) :
                new ObjectParameter("Costo_Articulo", typeof(double));
    
            var costo_Anterior_ArticuloParameter = costo_Anterior_Articulo.HasValue ?
                new ObjectParameter("Costo_Anterior_Articulo", costo_Anterior_Articulo) :
                new ObjectParameter("Costo_Anterior_Articulo", typeof(double));
    
            var id_ProveedorParameter = id_Proveedor.HasValue ?
                new ObjectParameter("Id_Proveedor", id_Proveedor) :
                new ObjectParameter("Id_Proveedor", typeof(int));
    
            var id_PresentacionParameter = id_Presentacion.HasValue ?
                new ObjectParameter("Id_Presentacion", id_Presentacion) :
                new ObjectParameter("Id_Presentacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Articulos_Update", id_ArticuloParameter, codigo_ArticuloParameter, nombre_ArticuloParameter, descripcion_ArticuloParameter, cantidad_ArticuloParameter, costo_ArticuloParameter, costo_Anterior_ArticuloParameter, id_ProveedorParameter, id_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_ArticulosRetornaID_Result> pa_ArticulosRetornaID(Nullable<int> id_Articulo)
        {
            var id_ArticuloParameter = id_Articulo.HasValue ?
                new ObjectParameter("Id_Articulo", id_Articulo) :
                new ObjectParameter("Id_Articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ArticulosRetornaID_Result>("pa_ArticulosRetornaID", id_ArticuloParameter);
        }
    
        public virtual ObjectResult<pa_Costos_BusquedaCodigoArt_Result> pa_Costos_BusquedaCodigoArt(string codigo_Articulo)
        {
            var codigo_ArticuloParameter = codigo_Articulo != null ?
                new ObjectParameter("Codigo_Articulo", codigo_Articulo) :
                new ObjectParameter("Codigo_Articulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Costos_BusquedaCodigoArt_Result>("pa_Costos_BusquedaCodigoArt", codigo_ArticuloParameter);
        }
    
        public virtual int pa_CrearRespaldo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CrearRespaldo");
        }
    
        public virtual ObjectResult<pa_EstadoUsuario_Select_Result> pa_EstadoUsuario_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_EstadoUsuario_Select_Result>("pa_EstadoUsuario_Select");
        }
    
        public virtual ObjectResult<pa_Paises_ExistePais_Result> pa_Paises_ExistePais(string nombrePais)
        {
            var nombrePaisParameter = nombrePais != null ?
                new ObjectParameter("NombrePais", nombrePais) :
                new ObjectParameter("NombrePais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Paises_ExistePais_Result>("pa_Paises_ExistePais", nombrePaisParameter);
        }
    
        public virtual int pa_Paises_Insert(string nombre_Pais, string sigla_Pais, string moneda_Pais)
        {
            var nombre_PaisParameter = nombre_Pais != null ?
                new ObjectParameter("Nombre_Pais", nombre_Pais) :
                new ObjectParameter("Nombre_Pais", typeof(string));
    
            var sigla_PaisParameter = sigla_Pais != null ?
                new ObjectParameter("Sigla_Pais", sigla_Pais) :
                new ObjectParameter("Sigla_Pais", typeof(string));
    
            var moneda_PaisParameter = moneda_Pais != null ?
                new ObjectParameter("Moneda_Pais", moneda_Pais) :
                new ObjectParameter("Moneda_Pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Paises_Insert", nombre_PaisParameter, sigla_PaisParameter, moneda_PaisParameter);
        }
    
        public virtual ObjectResult<pa_Paises_Select_Result> pa_Paises_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Paises_Select_Result>("pa_Paises_Select");
        }
    
        public virtual int pa_Paises_Update(Nullable<int> id_Pais, string nombre_Pais, string sigla_Pais, string moneda_Pais)
        {
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            var nombre_PaisParameter = nombre_Pais != null ?
                new ObjectParameter("Nombre_Pais", nombre_Pais) :
                new ObjectParameter("Nombre_Pais", typeof(string));
    
            var sigla_PaisParameter = sigla_Pais != null ?
                new ObjectParameter("Sigla_Pais", sigla_Pais) :
                new ObjectParameter("Sigla_Pais", typeof(string));
    
            var moneda_PaisParameter = moneda_Pais != null ?
                new ObjectParameter("Moneda_Pais", moneda_Pais) :
                new ObjectParameter("Moneda_Pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Paises_Update", id_PaisParameter, nombre_PaisParameter, sigla_PaisParameter, moneda_PaisParameter);
        }
    
        public virtual ObjectResult<pa_PaisesRetornaID_Result> pa_PaisesRetornaID(Nullable<int> id_Pais)
        {
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PaisesRetornaID_Result>("pa_PaisesRetornaID", id_PaisParameter);
        }
    
        public virtual ObjectResult<pa_Permisos_Select_Result> pa_Permisos_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Permisos_Select_Result>("pa_Permisos_Select");
        }
    
        public virtual int pa_Permisos_Update(Nullable<int> id_Usuario, Nullable<int> id_Estado_Usuario, Nullable<int> id_Tipo_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            var id_Estado_UsuarioParameter = id_Estado_Usuario.HasValue ?
                new ObjectParameter("Id_Estado_Usuario", id_Estado_Usuario) :
                new ObjectParameter("Id_Estado_Usuario", typeof(int));
    
            var id_Tipo_UsuarioParameter = id_Tipo_Usuario.HasValue ?
                new ObjectParameter("Id_Tipo_Usuario", id_Tipo_Usuario) :
                new ObjectParameter("Id_Tipo_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Permisos_Update", id_UsuarioParameter, id_Estado_UsuarioParameter, id_Tipo_UsuarioParameter);
        }
    
        public virtual ObjectResult<pa_PermisosRetornaID_Result> pa_PermisosRetornaID(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PermisosRetornaID_Result>("pa_PermisosRetornaID", id_UsuarioParameter);
        }
    
        public virtual ObjectResult<pa_Presentaciones_ExistePresentacion_Result> pa_Presentaciones_ExistePresentacion(string nombre_Presentacion)
        {
            var nombre_PresentacionParameter = nombre_Presentacion != null ?
                new ObjectParameter("Nombre_Presentacion", nombre_Presentacion) :
                new ObjectParameter("Nombre_Presentacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Presentaciones_ExistePresentacion_Result>("pa_Presentaciones_ExistePresentacion", nombre_PresentacionParameter);
        }
    
        public virtual int pa_Presentaciones_Insert(string nombre_Presentacion)
        {
            var nombre_PresentacionParameter = nombre_Presentacion != null ?
                new ObjectParameter("Nombre_Presentacion", nombre_Presentacion) :
                new ObjectParameter("Nombre_Presentacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Presentaciones_Insert", nombre_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_Presentaciones_Select_Result> pa_Presentaciones_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Presentaciones_Select_Result>("pa_Presentaciones_Select");
        }
    
        public virtual int pa_Presentaciones_Update(Nullable<int> id_Presentacion, string nombre_Presentacion)
        {
            var id_PresentacionParameter = id_Presentacion.HasValue ?
                new ObjectParameter("Id_Presentacion", id_Presentacion) :
                new ObjectParameter("Id_Presentacion", typeof(int));
    
            var nombre_PresentacionParameter = nombre_Presentacion != null ?
                new ObjectParameter("Nombre_Presentacion", nombre_Presentacion) :
                new ObjectParameter("Nombre_Presentacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Presentaciones_Update", id_PresentacionParameter, nombre_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_PresentacionesRetornaID_Result> pa_PresentacionesRetornaID(Nullable<int> id_Presentacion)
        {
            var id_PresentacionParameter = id_Presentacion.HasValue ?
                new ObjectParameter("Id_Presentacion", id_Presentacion) :
                new ObjectParameter("Id_Presentacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PresentacionesRetornaID_Result>("pa_PresentacionesRetornaID", id_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_Proveedores_ExisteProveedor_Result> pa_Proveedores_ExisteProveedor(string codigo_Proveedor, string nombre_Proveedor)
        {
            var codigo_ProveedorParameter = codigo_Proveedor != null ?
                new ObjectParameter("Codigo_Proveedor", codigo_Proveedor) :
                new ObjectParameter("Codigo_Proveedor", typeof(string));
    
            var nombre_ProveedorParameter = nombre_Proveedor != null ?
                new ObjectParameter("Nombre_Proveedor", nombre_Proveedor) :
                new ObjectParameter("Nombre_Proveedor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Proveedores_ExisteProveedor_Result>("pa_Proveedores_ExisteProveedor", codigo_ProveedorParameter, nombre_ProveedorParameter);
        }
    
        public virtual int pa_Proveedores_Insert(string nombre_Proveedor, string codigo_Proveedor, Nullable<int> id_Pais)
        {
            var nombre_ProveedorParameter = nombre_Proveedor != null ?
                new ObjectParameter("Nombre_Proveedor", nombre_Proveedor) :
                new ObjectParameter("Nombre_Proveedor", typeof(string));
    
            var codigo_ProveedorParameter = codigo_Proveedor != null ?
                new ObjectParameter("Codigo_Proveedor", codigo_Proveedor) :
                new ObjectParameter("Codigo_Proveedor", typeof(string));
    
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Proveedores_Insert", nombre_ProveedorParameter, codigo_ProveedorParameter, id_PaisParameter);
        }
    
        public virtual ObjectResult<pa_Proveedores_Select_Result> pa_Proveedores_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Proveedores_Select_Result>("pa_Proveedores_Select");
        }
    
        public virtual int pa_Proveedores_Update(Nullable<int> id_Proveedor, string codigo_Proveedor, string nombre_Proveedor, Nullable<int> id_Pais)
        {
            var id_ProveedorParameter = id_Proveedor.HasValue ?
                new ObjectParameter("Id_Proveedor", id_Proveedor) :
                new ObjectParameter("Id_Proveedor", typeof(int));
    
            var codigo_ProveedorParameter = codigo_Proveedor != null ?
                new ObjectParameter("Codigo_Proveedor", codigo_Proveedor) :
                new ObjectParameter("Codigo_Proveedor", typeof(string));
    
            var nombre_ProveedorParameter = nombre_Proveedor != null ?
                new ObjectParameter("Nombre_Proveedor", nombre_Proveedor) :
                new ObjectParameter("Nombre_Proveedor", typeof(string));
    
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Proveedores_Update", id_ProveedorParameter, codigo_ProveedorParameter, nombre_ProveedorParameter, id_PaisParameter);
        }
    
        public virtual ObjectResult<pa_ProveedoresRetornaID_Result> pa_ProveedoresRetornaID(Nullable<int> id_Proveedor)
        {
            var id_ProveedorParameter = id_Proveedor.HasValue ?
                new ObjectParameter("Id_Proveedor", id_Proveedor) :
                new ObjectParameter("Id_Proveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ProveedoresRetornaID_Result>("pa_ProveedoresRetornaID", id_ProveedorParameter);
        }
    
        public virtual ObjectResult<pa_RetornaArticulosAC_Result> pa_RetornaArticulosAC(string codigo_Articulo)
        {
            var codigo_ArticuloParameter = codigo_Articulo != null ?
                new ObjectParameter("Codigo_Articulo", codigo_Articulo) :
                new ObjectParameter("Codigo_Articulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_RetornaArticulosAC_Result>("pa_RetornaArticulosAC", codigo_ArticuloParameter);
        }
    
        public virtual ObjectResult<pa_RetornaUsuarioCorreoPwd_Select_Result> pa_RetornaUsuarioCorreoPwd_Select(string correo, string contrasena)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_RetornaUsuarioCorreoPwd_Select_Result>("pa_RetornaUsuarioCorreoPwd_Select", correoParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<pa_TipoUsuario_Select_Result> pa_TipoUsuario_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_TipoUsuario_Select_Result>("pa_TipoUsuario_Select");
        }
    
        public virtual int pa_Usuarios_Insert(string nombre_Completo, string correo_Electronico, string contrasena_Usuario, Nullable<int> id_Tipo_Usuario, Nullable<int> id_Estado_Usuario)
        {
            var nombre_CompletoParameter = nombre_Completo != null ?
                new ObjectParameter("Nombre_Completo", nombre_Completo) :
                new ObjectParameter("Nombre_Completo", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var contrasena_UsuarioParameter = contrasena_Usuario != null ?
                new ObjectParameter("Contrasena_Usuario", contrasena_Usuario) :
                new ObjectParameter("Contrasena_Usuario", typeof(string));
    
            var id_Tipo_UsuarioParameter = id_Tipo_Usuario.HasValue ?
                new ObjectParameter("Id_Tipo_Usuario", id_Tipo_Usuario) :
                new ObjectParameter("Id_Tipo_Usuario", typeof(int));
    
            var id_Estado_UsuarioParameter = id_Estado_Usuario.HasValue ?
                new ObjectParameter("Id_Estado_Usuario", id_Estado_Usuario) :
                new ObjectParameter("Id_Estado_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Usuarios_Insert", nombre_CompletoParameter, correo_ElectronicoParameter, contrasena_UsuarioParameter, id_Tipo_UsuarioParameter, id_Estado_UsuarioParameter);
        }
    
        public virtual ObjectResult<pa_Usuarios_Select_Result> pa_Usuarios_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Usuarios_Select_Result>("pa_Usuarios_Select");
        }
    
        public virtual ObjectResult<pa_Usuarios_SelectTodo_Result> pa_Usuarios_SelectTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Usuarios_SelectTodo_Result>("pa_Usuarios_SelectTodo");
        }
    
        public virtual ObjectResult<pa_UsuariosRetornaID_Result> pa_UsuariosRetornaID(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_UsuariosRetornaID_Result>("pa_UsuariosRetornaID", id_UsuarioParameter);
        }
    
        public virtual int pa_UsuariosUpdate(string nombre_Completo, string correo_Electronico, Nullable<int> id_Usuario)
        {
            var nombre_CompletoParameter = nombre_Completo != null ?
                new ObjectParameter("Nombre_Completo", nombre_Completo) :
                new ObjectParameter("Nombre_Completo", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_UsuariosUpdate", nombre_CompletoParameter, correo_ElectronicoParameter, id_UsuarioParameter);
        }
    
        public virtual ObjectResult<pa_VerificarCorreoRecuperacionPass_Result> pa_VerificarCorreoRecuperacionPass(string correo_Electronico)
        {
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_VerificarCorreoRecuperacionPass_Result>("pa_VerificarCorreoRecuperacionPass", correo_ElectronicoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
