//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLithio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LithioBDEntities : DbContext
    {
        public LithioBDEntities()
            : base("name=LithioBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Articulos> Articulos { get; set; }
        public DbSet<Costos> Costos { get; set; }
        public DbSet<Estado_Usuario> Estado_Usuario { get; set; }
        public DbSet<Paises> Paises { get; set; }
        public DbSet<Presentaciones> Presentaciones { get; set; }
        public DbSet<Proveedores> Proveedores { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int pa_Paises_Insert(string nombre_Pais, string sigla_Pais, string moneda_Pais)
        {
            var nombre_PaisParameter = nombre_Pais != null ?
                new ObjectParameter("Nombre_Pais", nombre_Pais) :
                new ObjectParameter("Nombre_Pais", typeof(string));
    
            var sigla_PaisParameter = sigla_Pais != null ?
                new ObjectParameter("Sigla_Pais", sigla_Pais) :
                new ObjectParameter("Sigla_Pais", typeof(string));
    
            var moneda_PaisParameter = moneda_Pais != null ?
                new ObjectParameter("Moneda_Pais", moneda_Pais) :
                new ObjectParameter("Moneda_Pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Paises_Insert", nombre_PaisParameter, sigla_PaisParameter, moneda_PaisParameter);
        }
    
        public virtual ObjectResult<pa_Paises_Select_Result> pa_Paises_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Paises_Select_Result>("pa_Paises_Select");
        }
    
        public virtual int pa_Paises_Update(Nullable<int> id_Pais, string nombre_Pais, string sigla_Pais, string moneda_Pais)
        {
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            var nombre_PaisParameter = nombre_Pais != null ?
                new ObjectParameter("Nombre_Pais", nombre_Pais) :
                new ObjectParameter("Nombre_Pais", typeof(string));
    
            var sigla_PaisParameter = sigla_Pais != null ?
                new ObjectParameter("Sigla_Pais", sigla_Pais) :
                new ObjectParameter("Sigla_Pais", typeof(string));
    
            var moneda_PaisParameter = moneda_Pais != null ?
                new ObjectParameter("Moneda_Pais", moneda_Pais) :
                new ObjectParameter("Moneda_Pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Paises_Update", id_PaisParameter, nombre_PaisParameter, sigla_PaisParameter, moneda_PaisParameter);
        }
    
        public virtual ObjectResult<pa_PaisesRetornaID_Result> pa_PaisesRetornaID(Nullable<int> id_Pais)
        {
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PaisesRetornaID_Result>("pa_PaisesRetornaID", id_PaisParameter);
        }
    
        public virtual ObjectResult<pa_Permisos_Select_Result> pa_Permisos_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Permisos_Select_Result>("pa_Permisos_Select");
        }
    
        public virtual int pa_Presentaciones_Insert(string nombre_Presentacion)
        {
            var nombre_PresentacionParameter = nombre_Presentacion != null ?
                new ObjectParameter("Nombre_Presentacion", nombre_Presentacion) :
                new ObjectParameter("Nombre_Presentacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Presentaciones_Insert", nombre_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_Presentaciones_Select_Result> pa_Presentaciones_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Presentaciones_Select_Result>("pa_Presentaciones_Select");
        }
    
        public virtual int pa_Presentaciones_Update(Nullable<int> id_Presentacion, string nombre_Presentacion)
        {
            var id_PresentacionParameter = id_Presentacion.HasValue ?
                new ObjectParameter("Id_Presentacion", id_Presentacion) :
                new ObjectParameter("Id_Presentacion", typeof(int));
    
            var nombre_PresentacionParameter = nombre_Presentacion != null ?
                new ObjectParameter("Nombre_Presentacion", nombre_Presentacion) :
                new ObjectParameter("Nombre_Presentacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Presentaciones_Update", id_PresentacionParameter, nombre_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_PresentacionesRetornaID_Result> pa_PresentacionesRetornaID(Nullable<int> id_Presentacion)
        {
            var id_PresentacionParameter = id_Presentacion.HasValue ?
                new ObjectParameter("Id_Presentacion", id_Presentacion) :
                new ObjectParameter("Id_Presentacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PresentacionesRetornaID_Result>("pa_PresentacionesRetornaID", id_PresentacionParameter);
        }
    
        public virtual int pa_Proveedores_Insert(string nombre_Proveedor, string codigo_Proveedor, Nullable<int> id_Pais)
        {
            var nombre_ProveedorParameter = nombre_Proveedor != null ?
                new ObjectParameter("Nombre_Proveedor", nombre_Proveedor) :
                new ObjectParameter("Nombre_Proveedor", typeof(string));
    
            var codigo_ProveedorParameter = codigo_Proveedor != null ?
                new ObjectParameter("Codigo_Proveedor", codigo_Proveedor) :
                new ObjectParameter("Codigo_Proveedor", typeof(string));
    
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Proveedores_Insert", nombre_ProveedorParameter, codigo_ProveedorParameter, id_PaisParameter);
        }
    
        public virtual ObjectResult<pa_Proveedores_Select_Result> pa_Proveedores_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Proveedores_Select_Result>("pa_Proveedores_Select");
        }
    
        public virtual int pa_Proveedores_Update(Nullable<int> id_Proveedor, string codigo_Proveedor, string nombre_Proveedor, Nullable<int> id_Pais)
        {
            var id_ProveedorParameter = id_Proveedor.HasValue ?
                new ObjectParameter("Id_Proveedor", id_Proveedor) :
                new ObjectParameter("Id_Proveedor", typeof(int));
    
            var codigo_ProveedorParameter = codigo_Proveedor != null ?
                new ObjectParameter("Codigo_Proveedor", codigo_Proveedor) :
                new ObjectParameter("Codigo_Proveedor", typeof(string));
    
            var nombre_ProveedorParameter = nombre_Proveedor != null ?
                new ObjectParameter("Nombre_Proveedor", nombre_Proveedor) :
                new ObjectParameter("Nombre_Proveedor", typeof(string));
    
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Proveedores_Update", id_ProveedorParameter, codigo_ProveedorParameter, nombre_ProveedorParameter, id_PaisParameter);
        }
    
        public virtual ObjectResult<pa_ProveedoresRetornaID_Result> pa_ProveedoresRetornaID(Nullable<int> id_Proveedor)
        {
            var id_ProveedorParameter = id_Proveedor.HasValue ?
                new ObjectParameter("Id_Proveedor", id_Proveedor) :
                new ObjectParameter("Id_Proveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ProveedoresRetornaID_Result>("pa_ProveedoresRetornaID", id_ProveedorParameter);
        }
    
        public virtual ObjectResult<pa_RetornaUsuarioCorreoPwd_Select_Result> pa_RetornaUsuarioCorreoPwd_Select(string correo, string contrasena)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_RetornaUsuarioCorreoPwd_Select_Result>("pa_RetornaUsuarioCorreoPwd_Select", correoParameter, contrasenaParameter);
        }
    
        public virtual int pa_Usuarios_Insert(string primer_Nombre, string primer_Apellido, string segundo_Apellido, string correo_Electronico, string contrasena_Usuario, Nullable<int> id_Tipo_Usuario, Nullable<int> id_Estado_Usuario)
        {
            var primer_NombreParameter = primer_Nombre != null ?
                new ObjectParameter("Primer_Nombre", primer_Nombre) :
                new ObjectParameter("Primer_Nombre", typeof(string));
    
            var primer_ApellidoParameter = primer_Apellido != null ?
                new ObjectParameter("Primer_Apellido", primer_Apellido) :
                new ObjectParameter("Primer_Apellido", typeof(string));
    
            var segundo_ApellidoParameter = segundo_Apellido != null ?
                new ObjectParameter("Segundo_Apellido", segundo_Apellido) :
                new ObjectParameter("Segundo_Apellido", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var contrasena_UsuarioParameter = contrasena_Usuario != null ?
                new ObjectParameter("Contrasena_Usuario", contrasena_Usuario) :
                new ObjectParameter("Contrasena_Usuario", typeof(string));
    
            var id_Tipo_UsuarioParameter = id_Tipo_Usuario.HasValue ?
                new ObjectParameter("Id_Tipo_Usuario", id_Tipo_Usuario) :
                new ObjectParameter("Id_Tipo_Usuario", typeof(int));
    
            var id_Estado_UsuarioParameter = id_Estado_Usuario.HasValue ?
                new ObjectParameter("Id_Estado_Usuario", id_Estado_Usuario) :
                new ObjectParameter("Id_Estado_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Usuarios_Insert", primer_NombreParameter, primer_ApellidoParameter, segundo_ApellidoParameter, correo_ElectronicoParameter, contrasena_UsuarioParameter, id_Tipo_UsuarioParameter, id_Estado_UsuarioParameter);
        }
    
        public virtual ObjectResult<pa_Usuarios_Select_Result> pa_Usuarios_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Usuarios_Select_Result>("pa_Usuarios_Select");
        }
    
        public virtual ObjectResult<pa_Usuarios_SelectTodo_Result> pa_Usuarios_SelectTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Usuarios_SelectTodo_Result>("pa_Usuarios_SelectTodo");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
