//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLithio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LithioBDEntities : DbContext
    {
        public LithioBDEntities()
            : base("name=LithioBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Articulos> Articulos { get; set; }
        public DbSet<Costo_Concepto> Costo_Concepto { get; set; }
        public DbSet<Costo_ConceptoAux> Costo_ConceptoAux { get; set; }
        public DbSet<Costos> Costos { get; set; }
        public DbSet<Estado_Usuario> Estado_Usuario { get; set; }
        public DbSet<Paises> Paises { get; set; }
        public DbSet<Presentaciones> Presentaciones { get; set; }
        public DbSet<Proveedores> Proveedores { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int pa_ActualizarTokenRecuperacionPass(string correo_Electronico, string token)
        {
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_ActualizarTokenRecuperacionPass", correo_ElectronicoParameter, tokenParameter);
        }
    
        public virtual ObjectResult<pa_Articulos_ExisteArticulosCodigo_Result> pa_Articulos_ExisteArticulosCodigo(string codigo_Articulo)
        {
            var codigo_ArticuloParameter = codigo_Articulo != null ?
                new ObjectParameter("Codigo_Articulo", codigo_Articulo) :
                new ObjectParameter("Codigo_Articulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Articulos_ExisteArticulosCodigo_Result>("pa_Articulos_ExisteArticulosCodigo", codigo_ArticuloParameter);
        }
    
        public virtual int pa_Articulos_Insert(string codigo_Articulo, string nombre_Articulo, string descripcion_Articulo, Nullable<int> cantidad_Articulo, Nullable<double> costo_Articulo, Nullable<double> costo_Anterior_Articulo, Nullable<int> id_Proveedor, Nullable<int> id_Presentacion)
        {
            var codigo_ArticuloParameter = codigo_Articulo != null ?
                new ObjectParameter("Codigo_Articulo", codigo_Articulo) :
                new ObjectParameter("Codigo_Articulo", typeof(string));
    
            var nombre_ArticuloParameter = nombre_Articulo != null ?
                new ObjectParameter("Nombre_Articulo", nombre_Articulo) :
                new ObjectParameter("Nombre_Articulo", typeof(string));
    
            var descripcion_ArticuloParameter = descripcion_Articulo != null ?
                new ObjectParameter("Descripcion_Articulo", descripcion_Articulo) :
                new ObjectParameter("Descripcion_Articulo", typeof(string));
    
            var cantidad_ArticuloParameter = cantidad_Articulo.HasValue ?
                new ObjectParameter("Cantidad_Articulo", cantidad_Articulo) :
                new ObjectParameter("Cantidad_Articulo", typeof(int));
    
            var costo_ArticuloParameter = costo_Articulo.HasValue ?
                new ObjectParameter("Costo_Articulo", costo_Articulo) :
                new ObjectParameter("Costo_Articulo", typeof(double));
    
            var costo_Anterior_ArticuloParameter = costo_Anterior_Articulo.HasValue ?
                new ObjectParameter("Costo_Anterior_Articulo", costo_Anterior_Articulo) :
                new ObjectParameter("Costo_Anterior_Articulo", typeof(double));
    
            var id_ProveedorParameter = id_Proveedor.HasValue ?
                new ObjectParameter("Id_Proveedor", id_Proveedor) :
                new ObjectParameter("Id_Proveedor", typeof(int));
    
            var id_PresentacionParameter = id_Presentacion.HasValue ?
                new ObjectParameter("Id_Presentacion", id_Presentacion) :
                new ObjectParameter("Id_Presentacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Articulos_Insert", codigo_ArticuloParameter, nombre_ArticuloParameter, descripcion_ArticuloParameter, cantidad_ArticuloParameter, costo_ArticuloParameter, costo_Anterior_ArticuloParameter, id_ProveedorParameter, id_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_Articulos_Select_Result> pa_Articulos_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Articulos_Select_Result>("pa_Articulos_Select");
        }
    
        public virtual int pa_Articulos_Update(Nullable<int> id_Articulo, string codigo_Articulo, string nombre_Articulo, string descripcion_Articulo, Nullable<int> cantidad_Articulo, Nullable<double> costo_Articulo, Nullable<int> id_Proveedor, Nullable<int> id_Presentacion)
        {
            var id_ArticuloParameter = id_Articulo.HasValue ?
                new ObjectParameter("Id_Articulo", id_Articulo) :
                new ObjectParameter("Id_Articulo", typeof(int));
    
            var codigo_ArticuloParameter = codigo_Articulo != null ?
                new ObjectParameter("Codigo_Articulo", codigo_Articulo) :
                new ObjectParameter("Codigo_Articulo", typeof(string));
    
            var nombre_ArticuloParameter = nombre_Articulo != null ?
                new ObjectParameter("Nombre_Articulo", nombre_Articulo) :
                new ObjectParameter("Nombre_Articulo", typeof(string));
    
            var descripcion_ArticuloParameter = descripcion_Articulo != null ?
                new ObjectParameter("Descripcion_Articulo", descripcion_Articulo) :
                new ObjectParameter("Descripcion_Articulo", typeof(string));
    
            var cantidad_ArticuloParameter = cantidad_Articulo.HasValue ?
                new ObjectParameter("Cantidad_Articulo", cantidad_Articulo) :
                new ObjectParameter("Cantidad_Articulo", typeof(int));
    
            var costo_ArticuloParameter = costo_Articulo.HasValue ?
                new ObjectParameter("Costo_Articulo", costo_Articulo) :
                new ObjectParameter("Costo_Articulo", typeof(double));
    
            var id_ProveedorParameter = id_Proveedor.HasValue ?
                new ObjectParameter("Id_Proveedor", id_Proveedor) :
                new ObjectParameter("Id_Proveedor", typeof(int));
    
            var id_PresentacionParameter = id_Presentacion.HasValue ?
                new ObjectParameter("Id_Presentacion", id_Presentacion) :
                new ObjectParameter("Id_Presentacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Articulos_Update", id_ArticuloParameter, codigo_ArticuloParameter, nombre_ArticuloParameter, descripcion_ArticuloParameter, cantidad_ArticuloParameter, costo_ArticuloParameter, id_ProveedorParameter, id_PresentacionParameter);
        }
    
        public virtual int pa_Articulos_Update_CostoAnterior(Nullable<int> id_Articulo, Nullable<double> costo_Articulo)
        {
            var id_ArticuloParameter = id_Articulo.HasValue ?
                new ObjectParameter("Id_Articulo", id_Articulo) :
                new ObjectParameter("Id_Articulo", typeof(int));
    
            var costo_ArticuloParameter = costo_Articulo.HasValue ?
                new ObjectParameter("Costo_Articulo", costo_Articulo) :
                new ObjectParameter("Costo_Articulo", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Articulos_Update_CostoAnterior", id_ArticuloParameter, costo_ArticuloParameter);
        }
    
        public virtual ObjectResult<pa_ArticulosRetornaID_Result> pa_ArticulosRetornaID(Nullable<int> id_Articulo)
        {
            var id_ArticuloParameter = id_Articulo.HasValue ?
                new ObjectParameter("Id_Articulo", id_Articulo) :
                new ObjectParameter("Id_Articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ArticulosRetornaID_Result>("pa_ArticulosRetornaID", id_ArticuloParameter);
        }
    
        public virtual int pa_CosteoMontoMaritimo(Nullable<double> montoCosteoPorArticulo, Nullable<int> id_Costo_Concepto_AUX)
        {
            var montoCosteoPorArticuloParameter = montoCosteoPorArticulo.HasValue ?
                new ObjectParameter("MontoCosteoPorArticulo", montoCosteoPorArticulo) :
                new ObjectParameter("MontoCosteoPorArticulo", typeof(double));
    
            var id_Costo_Concepto_AUXParameter = id_Costo_Concepto_AUX.HasValue ?
                new ObjectParameter("Id_Costo_Concepto_AUX", id_Costo_Concepto_AUX) :
                new ObjectParameter("Id_Costo_Concepto_AUX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CosteoMontoMaritimo", montoCosteoPorArticuloParameter, id_Costo_Concepto_AUXParameter);
        }
    
        public virtual int pa_CosteoMontoTerrestre(Nullable<double> montoCosteoPorArticuloTer, Nullable<int> id_Costo_Concepto_AUX)
        {
            var montoCosteoPorArticuloTerParameter = montoCosteoPorArticuloTer.HasValue ?
                new ObjectParameter("MontoCosteoPorArticuloTer", montoCosteoPorArticuloTer) :
                new ObjectParameter("MontoCosteoPorArticuloTer", typeof(double));
    
            var id_Costo_Concepto_AUXParameter = id_Costo_Concepto_AUX.HasValue ?
                new ObjectParameter("Id_Costo_Concepto_AUX", id_Costo_Concepto_AUX) :
                new ObjectParameter("Id_Costo_Concepto_AUX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CosteoMontoTerrestre", montoCosteoPorArticuloTerParameter, id_Costo_Concepto_AUXParameter);
        }
    
        public virtual int pa_CosteoMontoTotal(Nullable<double> total_Costeo, Nullable<int> id_Costo_Concepto_AUX)
        {
            var total_CosteoParameter = total_Costeo.HasValue ?
                new ObjectParameter("Total_Costeo", total_Costeo) :
                new ObjectParameter("Total_Costeo", typeof(double));
    
            var id_Costo_Concepto_AUXParameter = id_Costo_Concepto_AUX.HasValue ?
                new ObjectParameter("Id_Costo_Concepto_AUX", id_Costo_Concepto_AUX) :
                new ObjectParameter("Id_Costo_Concepto_AUX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CosteoMontoTotal", total_CosteoParameter, id_Costo_Concepto_AUXParameter);
        }
    
        public virtual int pa_CosteoMontoTotal_CosteoPorArticuloMar(Nullable<double> total_CosteoPorArticuloMar, Nullable<int> id_Costo_Concepto_AUX)
        {
            var total_CosteoPorArticuloMarParameter = total_CosteoPorArticuloMar.HasValue ?
                new ObjectParameter("Total_CosteoPorArticuloMar", total_CosteoPorArticuloMar) :
                new ObjectParameter("Total_CosteoPorArticuloMar", typeof(double));
    
            var id_Costo_Concepto_AUXParameter = id_Costo_Concepto_AUX.HasValue ?
                new ObjectParameter("Id_Costo_Concepto_AUX", id_Costo_Concepto_AUX) :
                new ObjectParameter("Id_Costo_Concepto_AUX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CosteoMontoTotal_CosteoPorArticuloMar", total_CosteoPorArticuloMarParameter, id_Costo_Concepto_AUXParameter);
        }
    
        public virtual int pa_CosteoMontoTotal_CosteoPorArticuloTer(Nullable<double> total_CosteoPorArticuloTer, Nullable<int> id_Costo_Concepto_AUX)
        {
            var total_CosteoPorArticuloTerParameter = total_CosteoPorArticuloTer.HasValue ?
                new ObjectParameter("Total_CosteoPorArticuloTer", total_CosteoPorArticuloTer) :
                new ObjectParameter("Total_CosteoPorArticuloTer", typeof(double));
    
            var id_Costo_Concepto_AUXParameter = id_Costo_Concepto_AUX.HasValue ?
                new ObjectParameter("Id_Costo_Concepto_AUX", id_Costo_Concepto_AUX) :
                new ObjectParameter("Id_Costo_Concepto_AUX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CosteoMontoTotal_CosteoPorArticuloTer", total_CosteoPorArticuloTerParameter, id_Costo_Concepto_AUXParameter);
        }
    
        public virtual ObjectResult<pa_CosteoRetornaID_Result> pa_CosteoRetornaID(Nullable<int> id_Costo_Concepto_AUX)
        {
            var id_Costo_Concepto_AUXParameter = id_Costo_Concepto_AUX.HasValue ?
                new ObjectParameter("Id_Costo_Concepto_AUX", id_Costo_Concepto_AUX) :
                new ObjectParameter("Id_Costo_Concepto_AUX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CosteoRetornaID_Result>("pa_CosteoRetornaID", id_Costo_Concepto_AUXParameter);
        }
    
        public virtual int pa_Costo_ConceptoAux(Nullable<int> id_costo, string codigo_articulo, string nombre_articulo, Nullable<int> id_presentacion, string nombre_presentacion, Nullable<int> id_proveedor, string nombre_proveedor, Nullable<double> unidades_articulos, Nullable<double> costo_por_unidad_dolares, Nullable<double> total_costo_dolares)
        {
            var id_costoParameter = id_costo.HasValue ?
                new ObjectParameter("id_costo", id_costo) :
                new ObjectParameter("id_costo", typeof(int));
    
            var codigo_articuloParameter = codigo_articulo != null ?
                new ObjectParameter("codigo_articulo", codigo_articulo) :
                new ObjectParameter("codigo_articulo", typeof(string));
    
            var nombre_articuloParameter = nombre_articulo != null ?
                new ObjectParameter("nombre_articulo", nombre_articulo) :
                new ObjectParameter("nombre_articulo", typeof(string));
    
            var id_presentacionParameter = id_presentacion.HasValue ?
                new ObjectParameter("id_presentacion", id_presentacion) :
                new ObjectParameter("id_presentacion", typeof(int));
    
            var nombre_presentacionParameter = nombre_presentacion != null ?
                new ObjectParameter("nombre_presentacion", nombre_presentacion) :
                new ObjectParameter("nombre_presentacion", typeof(string));
    
            var id_proveedorParameter = id_proveedor.HasValue ?
                new ObjectParameter("id_proveedor", id_proveedor) :
                new ObjectParameter("id_proveedor", typeof(int));
    
            var nombre_proveedorParameter = nombre_proveedor != null ?
                new ObjectParameter("nombre_proveedor", nombre_proveedor) :
                new ObjectParameter("nombre_proveedor", typeof(string));
    
            var unidades_articulosParameter = unidades_articulos.HasValue ?
                new ObjectParameter("unidades_articulos", unidades_articulos) :
                new ObjectParameter("unidades_articulos", typeof(double));
    
            var costo_por_unidad_dolaresParameter = costo_por_unidad_dolares.HasValue ?
                new ObjectParameter("costo_por_unidad_dolares", costo_por_unidad_dolares) :
                new ObjectParameter("costo_por_unidad_dolares", typeof(double));
    
            var total_costo_dolaresParameter = total_costo_dolares.HasValue ?
                new ObjectParameter("total_costo_dolares", total_costo_dolares) :
                new ObjectParameter("total_costo_dolares", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Costo_ConceptoAux", id_costoParameter, codigo_articuloParameter, nombre_articuloParameter, id_presentacionParameter, nombre_presentacionParameter, id_proveedorParameter, nombre_proveedorParameter, unidades_articulosParameter, costo_por_unidad_dolaresParameter, total_costo_dolaresParameter);
        }
    
        public virtual ObjectResult<pa_CostoAUX_OrdenarProveedor_Result> pa_CostoAUX_OrdenarProveedor(Nullable<int> id_Costeo)
        {
            var id_CosteoParameter = id_Costeo.HasValue ?
                new ObjectParameter("Id_Costeo", id_Costeo) :
                new ObjectParameter("Id_Costeo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CostoAUX_OrdenarProveedor_Result>("pa_CostoAUX_OrdenarProveedor", id_CosteoParameter);
        }
    
        public virtual ObjectResult<pa_CostoContarProveedor_Result> pa_CostoContarProveedor(Nullable<int> id_costo)
        {
            var id_costoParameter = id_costo.HasValue ?
                new ObjectParameter("id_costo", id_costo) :
                new ObjectParameter("id_costo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CostoContarProveedor_Result>("pa_CostoContarProveedor", id_costoParameter);
        }
    
        public virtual int pa_CostoDistCostoMaritimoUpdate(Nullable<double> distCostoMaritimo, Nullable<int> id_Costo_Concepto_AUX)
        {
            var distCostoMaritimoParameter = distCostoMaritimo.HasValue ?
                new ObjectParameter("DistCostoMaritimo", distCostoMaritimo) :
                new ObjectParameter("DistCostoMaritimo", typeof(double));
    
            var id_Costo_Concepto_AUXParameter = id_Costo_Concepto_AUX.HasValue ?
                new ObjectParameter("Id_Costo_Concepto_AUX", id_Costo_Concepto_AUX) :
                new ObjectParameter("Id_Costo_Concepto_AUX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CostoDistCostoMaritimoUpdate", distCostoMaritimoParameter, id_Costo_Concepto_AUXParameter);
        }
    
        public virtual int pa_CostoDistCostoTerrestreUpdate(Nullable<double> distCostoTerrestre, Nullable<int> id_Costo_Concepto_AUX)
        {
            var distCostoTerrestreParameter = distCostoTerrestre.HasValue ?
                new ObjectParameter("DistCostoTerrestre", distCostoTerrestre) :
                new ObjectParameter("DistCostoTerrestre", typeof(double));
    
            var id_Costo_Concepto_AUXParameter = id_Costo_Concepto_AUX.HasValue ?
                new ObjectParameter("Id_Costo_Concepto_AUX", id_Costo_Concepto_AUX) :
                new ObjectParameter("Id_Costo_Concepto_AUX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CostoDistCostoTerrestreUpdate", distCostoTerrestreParameter, id_Costo_Concepto_AUXParameter);
        }
    
        public virtual ObjectResult<pa_CostoObtenerImpuestos_Result> pa_CostoObtenerImpuestos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CostoObtenerImpuestos_Result>("pa_CostoObtenerImpuestos");
        }
    
        public virtual int pa_CostoProbUpdate(Nullable<int> id_costo, Nullable<int> id_costo_concepto_aux, string nombre_proveedor, Nullable<double> probCostoTotalCompra)
        {
            var id_costoParameter = id_costo.HasValue ?
                new ObjectParameter("id_costo", id_costo) :
                new ObjectParameter("id_costo", typeof(int));
    
            var id_costo_concepto_auxParameter = id_costo_concepto_aux.HasValue ?
                new ObjectParameter("id_costo_concepto_aux", id_costo_concepto_aux) :
                new ObjectParameter("id_costo_concepto_aux", typeof(int));
    
            var nombre_proveedorParameter = nombre_proveedor != null ?
                new ObjectParameter("nombre_proveedor", nombre_proveedor) :
                new ObjectParameter("nombre_proveedor", typeof(string));
    
            var probCostoTotalCompraParameter = probCostoTotalCompra.HasValue ?
                new ObjectParameter("ProbCostoTotalCompra", probCostoTotalCompra) :
                new ObjectParameter("ProbCostoTotalCompra", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CostoProbUpdate", id_costoParameter, id_costo_concepto_auxParameter, nombre_proveedorParameter, probCostoTotalCompraParameter);
        }
    
        public virtual ObjectResult<pa_Costos_BusquedaCodigoArt_Result> pa_Costos_BusquedaCodigoArt(string codigo_Articulo)
        {
            var codigo_ArticuloParameter = codigo_Articulo != null ?
                new ObjectParameter("Codigo_Articulo", codigo_Articulo) :
                new ObjectParameter("Codigo_Articulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Costos_BusquedaCodigoArt_Result>("pa_Costos_BusquedaCodigoArt", codigo_ArticuloParameter);
        }
    
        public virtual int pa_CrearRespaldo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CrearRespaldo");
        }
    
        public virtual ObjectResult<pa_EstadoUsuario_Select_Result> pa_EstadoUsuario_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_EstadoUsuario_Select_Result>("pa_EstadoUsuario_Select");
        }
    
        public virtual ObjectResult<pa_Paises_ExistePais_Result> pa_Paises_ExistePais(string nombrePais)
        {
            var nombrePaisParameter = nombrePais != null ?
                new ObjectParameter("NombrePais", nombrePais) :
                new ObjectParameter("NombrePais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Paises_ExistePais_Result>("pa_Paises_ExistePais", nombrePaisParameter);
        }
    
        public virtual int pa_Paises_Insert(string nombre_Pais, string sigla_Pais, string moneda_Pais)
        {
            var nombre_PaisParameter = nombre_Pais != null ?
                new ObjectParameter("Nombre_Pais", nombre_Pais) :
                new ObjectParameter("Nombre_Pais", typeof(string));
    
            var sigla_PaisParameter = sigla_Pais != null ?
                new ObjectParameter("Sigla_Pais", sigla_Pais) :
                new ObjectParameter("Sigla_Pais", typeof(string));
    
            var moneda_PaisParameter = moneda_Pais != null ?
                new ObjectParameter("Moneda_Pais", moneda_Pais) :
                new ObjectParameter("Moneda_Pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Paises_Insert", nombre_PaisParameter, sigla_PaisParameter, moneda_PaisParameter);
        }
    
        public virtual ObjectResult<pa_Paises_Select_Result> pa_Paises_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Paises_Select_Result>("pa_Paises_Select");
        }
    
        public virtual int pa_Paises_Update(Nullable<int> id_Pais, string nombre_Pais, string sigla_Pais, string moneda_Pais)
        {
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            var nombre_PaisParameter = nombre_Pais != null ?
                new ObjectParameter("Nombre_Pais", nombre_Pais) :
                new ObjectParameter("Nombre_Pais", typeof(string));
    
            var sigla_PaisParameter = sigla_Pais != null ?
                new ObjectParameter("Sigla_Pais", sigla_Pais) :
                new ObjectParameter("Sigla_Pais", typeof(string));
    
            var moneda_PaisParameter = moneda_Pais != null ?
                new ObjectParameter("Moneda_Pais", moneda_Pais) :
                new ObjectParameter("Moneda_Pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Paises_Update", id_PaisParameter, nombre_PaisParameter, sigla_PaisParameter, moneda_PaisParameter);
        }
    
        public virtual ObjectResult<pa_PaisesRetornaID_Result> pa_PaisesRetornaID(Nullable<int> id_Pais)
        {
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PaisesRetornaID_Result>("pa_PaisesRetornaID", id_PaisParameter);
        }
    
        public virtual ObjectResult<pa_Permisos_Select_Result> pa_Permisos_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Permisos_Select_Result>("pa_Permisos_Select");
        }
    
        public virtual int pa_Permisos_Update(Nullable<int> id_Usuario, Nullable<int> id_Estado_Usuario, Nullable<int> id_Tipo_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            var id_Estado_UsuarioParameter = id_Estado_Usuario.HasValue ?
                new ObjectParameter("Id_Estado_Usuario", id_Estado_Usuario) :
                new ObjectParameter("Id_Estado_Usuario", typeof(int));
    
            var id_Tipo_UsuarioParameter = id_Tipo_Usuario.HasValue ?
                new ObjectParameter("Id_Tipo_Usuario", id_Tipo_Usuario) :
                new ObjectParameter("Id_Tipo_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Permisos_Update", id_UsuarioParameter, id_Estado_UsuarioParameter, id_Tipo_UsuarioParameter);
        }
    
        public virtual ObjectResult<pa_PermisosRetornaID_Result> pa_PermisosRetornaID(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PermisosRetornaID_Result>("pa_PermisosRetornaID", id_UsuarioParameter);
        }
    
        public virtual ObjectResult<pa_Presentaciones_ExistePresentacion_Result> pa_Presentaciones_ExistePresentacion(string nombre_Presentacion)
        {
            var nombre_PresentacionParameter = nombre_Presentacion != null ?
                new ObjectParameter("Nombre_Presentacion", nombre_Presentacion) :
                new ObjectParameter("Nombre_Presentacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Presentaciones_ExistePresentacion_Result>("pa_Presentaciones_ExistePresentacion", nombre_PresentacionParameter);
        }
    
        public virtual int pa_Presentaciones_Insert(string nombre_Presentacion)
        {
            var nombre_PresentacionParameter = nombre_Presentacion != null ?
                new ObjectParameter("Nombre_Presentacion", nombre_Presentacion) :
                new ObjectParameter("Nombre_Presentacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Presentaciones_Insert", nombre_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_Presentaciones_Select_Result> pa_Presentaciones_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Presentaciones_Select_Result>("pa_Presentaciones_Select");
        }
    
        public virtual int pa_Presentaciones_Update(Nullable<int> id_Presentacion, string nombre_Presentacion)
        {
            var id_PresentacionParameter = id_Presentacion.HasValue ?
                new ObjectParameter("Id_Presentacion", id_Presentacion) :
                new ObjectParameter("Id_Presentacion", typeof(int));
    
            var nombre_PresentacionParameter = nombre_Presentacion != null ?
                new ObjectParameter("Nombre_Presentacion", nombre_Presentacion) :
                new ObjectParameter("Nombre_Presentacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Presentaciones_Update", id_PresentacionParameter, nombre_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_PresentacionesRetornaID_Result> pa_PresentacionesRetornaID(Nullable<int> id_Presentacion)
        {
            var id_PresentacionParameter = id_Presentacion.HasValue ?
                new ObjectParameter("Id_Presentacion", id_Presentacion) :
                new ObjectParameter("Id_Presentacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PresentacionesRetornaID_Result>("pa_PresentacionesRetornaID", id_PresentacionParameter);
        }
    
        public virtual ObjectResult<pa_Proveedores_ExisteProveedor_Result> pa_Proveedores_ExisteProveedor(string codigo_Proveedor, string nombre_Proveedor)
        {
            var codigo_ProveedorParameter = codigo_Proveedor != null ?
                new ObjectParameter("Codigo_Proveedor", codigo_Proveedor) :
                new ObjectParameter("Codigo_Proveedor", typeof(string));
    
            var nombre_ProveedorParameter = nombre_Proveedor != null ?
                new ObjectParameter("Nombre_Proveedor", nombre_Proveedor) :
                new ObjectParameter("Nombre_Proveedor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Proveedores_ExisteProveedor_Result>("pa_Proveedores_ExisteProveedor", codigo_ProveedorParameter, nombre_ProveedorParameter);
        }
    
        public virtual int pa_Proveedores_Insert(string nombre_Proveedor, string codigo_Proveedor, Nullable<int> id_Pais, string tiene_Costo_Maritimo, Nullable<decimal> costo_Maritimo, string tiene_Costo_Terrestre, Nullable<decimal> costo_Terrestre)
        {
            var nombre_ProveedorParameter = nombre_Proveedor != null ?
                new ObjectParameter("Nombre_Proveedor", nombre_Proveedor) :
                new ObjectParameter("Nombre_Proveedor", typeof(string));
    
            var codigo_ProveedorParameter = codigo_Proveedor != null ?
                new ObjectParameter("Codigo_Proveedor", codigo_Proveedor) :
                new ObjectParameter("Codigo_Proveedor", typeof(string));
    
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            var tiene_Costo_MaritimoParameter = tiene_Costo_Maritimo != null ?
                new ObjectParameter("Tiene_Costo_Maritimo", tiene_Costo_Maritimo) :
                new ObjectParameter("Tiene_Costo_Maritimo", typeof(string));
    
            var costo_MaritimoParameter = costo_Maritimo.HasValue ?
                new ObjectParameter("Costo_Maritimo", costo_Maritimo) :
                new ObjectParameter("Costo_Maritimo", typeof(decimal));
    
            var tiene_Costo_TerrestreParameter = tiene_Costo_Terrestre != null ?
                new ObjectParameter("Tiene_Costo_Terrestre", tiene_Costo_Terrestre) :
                new ObjectParameter("Tiene_Costo_Terrestre", typeof(string));
    
            var costo_TerrestreParameter = costo_Terrestre.HasValue ?
                new ObjectParameter("Costo_Terrestre", costo_Terrestre) :
                new ObjectParameter("Costo_Terrestre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Proveedores_Insert", nombre_ProveedorParameter, codigo_ProveedorParameter, id_PaisParameter, tiene_Costo_MaritimoParameter, costo_MaritimoParameter, tiene_Costo_TerrestreParameter, costo_TerrestreParameter);
        }
    
        public virtual ObjectResult<pa_Proveedores_Select_Result> pa_Proveedores_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Proveedores_Select_Result>("pa_Proveedores_Select");
        }
    
        public virtual int pa_Proveedores_Update(Nullable<int> id_Proveedor, string codigo_Proveedor, string nombre_Proveedor, Nullable<int> id_Pais, string tiene_Costo_Maritimo, Nullable<decimal> costo_Maritimo, string tiene_Costo_Terrestre, Nullable<decimal> costo_Terrestre)
        {
            var id_ProveedorParameter = id_Proveedor.HasValue ?
                new ObjectParameter("Id_Proveedor", id_Proveedor) :
                new ObjectParameter("Id_Proveedor", typeof(int));
    
            var codigo_ProveedorParameter = codigo_Proveedor != null ?
                new ObjectParameter("Codigo_Proveedor", codigo_Proveedor) :
                new ObjectParameter("Codigo_Proveedor", typeof(string));
    
            var nombre_ProveedorParameter = nombre_Proveedor != null ?
                new ObjectParameter("Nombre_Proveedor", nombre_Proveedor) :
                new ObjectParameter("Nombre_Proveedor", typeof(string));
    
            var id_PaisParameter = id_Pais.HasValue ?
                new ObjectParameter("Id_Pais", id_Pais) :
                new ObjectParameter("Id_Pais", typeof(int));
    
            var tiene_Costo_MaritimoParameter = tiene_Costo_Maritimo != null ?
                new ObjectParameter("Tiene_Costo_Maritimo", tiene_Costo_Maritimo) :
                new ObjectParameter("Tiene_Costo_Maritimo", typeof(string));
    
            var costo_MaritimoParameter = costo_Maritimo.HasValue ?
                new ObjectParameter("Costo_Maritimo", costo_Maritimo) :
                new ObjectParameter("Costo_Maritimo", typeof(decimal));
    
            var tiene_Costo_TerrestreParameter = tiene_Costo_Terrestre != null ?
                new ObjectParameter("Tiene_Costo_Terrestre", tiene_Costo_Terrestre) :
                new ObjectParameter("Tiene_Costo_Terrestre", typeof(string));
    
            var costo_TerrestreParameter = costo_Terrestre.HasValue ?
                new ObjectParameter("Costo_Terrestre", costo_Terrestre) :
                new ObjectParameter("Costo_Terrestre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Proveedores_Update", id_ProveedorParameter, codigo_ProveedorParameter, nombre_ProveedorParameter, id_PaisParameter, tiene_Costo_MaritimoParameter, costo_MaritimoParameter, tiene_Costo_TerrestreParameter, costo_TerrestreParameter);
        }
    
        public virtual ObjectResult<pa_ProveedoresRetornaID_Result> pa_ProveedoresRetornaID(Nullable<int> id_Proveedor)
        {
            var id_ProveedorParameter = id_Proveedor.HasValue ?
                new ObjectParameter("Id_Proveedor", id_Proveedor) :
                new ObjectParameter("Id_Proveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ProveedoresRetornaID_Result>("pa_ProveedoresRetornaID", id_ProveedorParameter);
        }
    
        public virtual ObjectResult<pa_ReporteListaCosteo_Result> pa_ReporteListaCosteo(Nullable<int> numero_Costeo, string dUA, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var numero_CosteoParameter = numero_Costeo.HasValue ?
                new ObjectParameter("Numero_Costeo", numero_Costeo) :
                new ObjectParameter("Numero_Costeo", typeof(int));
    
            var dUAParameter = dUA != null ?
                new ObjectParameter("DUA", dUA) :
                new ObjectParameter("DUA", typeof(string));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ReporteListaCosteo_Result>("pa_ReporteListaCosteo", numero_CosteoParameter, dUAParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<pa_RetornaArticulosAC_Result> pa_RetornaArticulosAC(string codigo_Articulo)
        {
            var codigo_ArticuloParameter = codigo_Articulo != null ?
                new ObjectParameter("Codigo_Articulo", codigo_Articulo) :
                new ObjectParameter("Codigo_Articulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_RetornaArticulosAC_Result>("pa_RetornaArticulosAC", codigo_ArticuloParameter);
        }
    
        public virtual ObjectResult<pa_RetornaUsuarioCorreoPwd_Select_Result> pa_RetornaUsuarioCorreoPwd_Select(string correo, string contrasena)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_RetornaUsuarioCorreoPwd_Select_Result>("pa_RetornaUsuarioCorreoPwd_Select", correoParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<pa_TipoUsuario_Select_Result> pa_TipoUsuario_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_TipoUsuario_Select_Result>("pa_TipoUsuario_Select");
        }
    
        public virtual int pa_updatePrecioFinalLineasCosteo(Nullable<int> id_costeo, string nombre_provedor, Nullable<double> precio_final_articulos)
        {
            var id_costeoParameter = id_costeo.HasValue ?
                new ObjectParameter("id_costeo", id_costeo) :
                new ObjectParameter("id_costeo", typeof(int));
    
            var nombre_provedorParameter = nombre_provedor != null ?
                new ObjectParameter("nombre_provedor", nombre_provedor) :
                new ObjectParameter("nombre_provedor", typeof(string));
    
            var precio_final_articulosParameter = precio_final_articulos.HasValue ?
                new ObjectParameter("precio_final_articulos", precio_final_articulos) :
                new ObjectParameter("precio_final_articulos", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_updatePrecioFinalLineasCosteo", id_costeoParameter, nombre_provedorParameter, precio_final_articulosParameter);
        }
    
        public virtual int pa_Usuarios_Insert(string nombre_Completo, string correo_Electronico, string contrasena_Usuario, Nullable<int> id_Tipo_Usuario, Nullable<int> id_Estado_Usuario)
        {
            var nombre_CompletoParameter = nombre_Completo != null ?
                new ObjectParameter("Nombre_Completo", nombre_Completo) :
                new ObjectParameter("Nombre_Completo", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var contrasena_UsuarioParameter = contrasena_Usuario != null ?
                new ObjectParameter("Contrasena_Usuario", contrasena_Usuario) :
                new ObjectParameter("Contrasena_Usuario", typeof(string));
    
            var id_Tipo_UsuarioParameter = id_Tipo_Usuario.HasValue ?
                new ObjectParameter("Id_Tipo_Usuario", id_Tipo_Usuario) :
                new ObjectParameter("Id_Tipo_Usuario", typeof(int));
    
            var id_Estado_UsuarioParameter = id_Estado_Usuario.HasValue ?
                new ObjectParameter("Id_Estado_Usuario", id_Estado_Usuario) :
                new ObjectParameter("Id_Estado_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Usuarios_Insert", nombre_CompletoParameter, correo_ElectronicoParameter, contrasena_UsuarioParameter, id_Tipo_UsuarioParameter, id_Estado_UsuarioParameter);
        }
    
        public virtual ObjectResult<pa_Usuarios_Select_Result> pa_Usuarios_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Usuarios_Select_Result>("pa_Usuarios_Select");
        }
    
        public virtual ObjectResult<pa_Usuarios_SelectTodo_Result> pa_Usuarios_SelectTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Usuarios_SelectTodo_Result>("pa_Usuarios_SelectTodo");
        }
    
        public virtual ObjectResult<pa_UsuariosRetornaID_Result> pa_UsuariosRetornaID(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_UsuariosRetornaID_Result>("pa_UsuariosRetornaID", id_UsuarioParameter);
        }
    
        public virtual int pa_UsuariosUpdate(string nombre_Completo, string correo_Electronico, Nullable<int> id_Usuario)
        {
            var nombre_CompletoParameter = nombre_Completo != null ?
                new ObjectParameter("Nombre_Completo", nombre_Completo) :
                new ObjectParameter("Nombre_Completo", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_UsuariosUpdate", nombre_CompletoParameter, correo_ElectronicoParameter, id_UsuarioParameter);
        }
    
        public virtual ObjectResult<pa_VerificarCorreoRecuperacionPass_Result> pa_VerificarCorreoRecuperacionPass(string correo_Electronico)
        {
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_VerificarCorreoRecuperacionPass_Result>("pa_VerificarCorreoRecuperacionPass", correo_ElectronicoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
