//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLithio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        public Paises()
        {
            this.Proveedores = new HashSet<Proveedores>();
        }
    
        public int Id_Pais { get; set; }
        public string Nombre_Pais { get; set; }
        public string Sigla_Pais { get; set; }
        public string Moneda_Pais { get; set; }
    
        public virtual ICollection<Proveedores> Proveedores { get; set; }
    }
}
