//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLithio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public Proveedores()
        {
            this.Articulos = new HashSet<Articulos>();
        }
    
        public int Id_Proveedor { get; set; }
        public string Codigo_Proveedor { get; set; }
        public string Nombre_Proveedor { get; set; }
        public int Id_Pais { get; set; }
    
        public virtual ICollection<Articulos> Articulos { get; set; }
        public virtual Paises Paises { get; set; }
    }
}
