//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLithio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Usuario
    {
        public Tipo_Usuario()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int Id_Tipo_Usuario { get; set; }
        public string Desc_Tipo_Usuario { get; set; }
    
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
