//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLithio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id_Usuario { get; set; }
        public string Nombre_Completo { get; set; }
        public string Correo_Electronico { get; set; }
        public string Contrasena_Usuario { get; set; }
        public int Id_Tipo_Usuario { get; set; }
        public int Id_Estado_Usuario { get; set; }
        public string Token_Recovery { get; set; }
    
        public virtual Estado_Usuario Estado_Usuario { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
    }
}
